// Generated by CodiumAI

import { render, screen } from "@testing-library/react";
import { Button } from "./Button";

describe('Button', () => {
    it('should render a button with the provided label and primary style by default', () => {
      const label = 'Submit';
      render(<Button label={label} />);

      expect(screen.getByRole('button')).toHaveTextContent(label);
      expect(screen.getByRole('button')).toHaveClass('btn_primary');
    });

    it('should render a button with the provided label and secondary style when type prop is set to "secondary"', () => {
      const label = 'Submit';

      render(<Button label={label} type="secondary" />);
  
      expect(screen.getByRole('button')).toHaveTextContent(label);
      expect(screen.getByRole('button')).toHaveClass('btn_secondary');
    });

});
