version: 2.1
jobs:
    build-and-test:
        docker:
            - image: cimg/node:20.11.0
        steps:
            - checkout
            - run:
                  name: update npm
                  command: "sudo npm install --unsafe-perm -g npm@latest"
            - run:
                  name: install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: run test
                  command: npm run test
            - run:
                  name: build app
                  command: npm run build