// Generated by CodiumAI

import { render, screen } from "@testing-library/react";
import { Header } from "./Header";

describe('Header', () => {

    // Renders a header element with class 'header'
    it('should render a header element with class \'header\'', () => {
      render(<Header />);
      const headerElement = screen.getByRole('banner');
      expect(headerElement).toHaveClass('header');
    });
});
