// Generated by CodiumAI

import { render } from "@testing-library/react";
import { HomePage } from "./HomePage";

describe('HomePage', () => {
    it('should return a div element containing the text "HomePage"', () => {
      const { getByText } = render(<HomePage />);
      const divElement = getByText('HomePage');
      expect(divElement).toBeInTheDocument();
    });
});
