// Generated by CodiumAI

import { act, render } from "@testing-library/react";
import { HomePage } from "./HomePage";
import {} from "../../store/isLoading"

describe('HomePage', () => {
    it('should return a div element containing the text "HomePage"', () => {
      window.alert = jest.fn();

      act(() => {

      });
    });
});
